### ISSUE TITLE
[BUG] Default OmegaT colors changed when the plugin's jar is present

### ISSUE THREAD

**Issue by kosivantsov** [omegat-org/glossary-renderer-plugin-skeleton#1]
**The Bug**
When the plugin jar is put into ~/.omegat/plugins, and OmegaT started, colors that weren't changed by users are changed. The layout provided by the plugin doesn't even need to be selected, the mere presence of the plugin is enough. 

When the jar is removed, default colors restore their default values.
This bug isn't observed for the colors that have been changed by the user prior to using this plugin. 

**Steps to Reproduce**
1. Build the jar
2. Place it into `~/.omegat/plugins` (or `/any/other/folder/plugins`, and then in the next step start OmegaT with that folder as the `config-dir`)
3. Start OmegaT (if needed, as `java -jar OmegaT.jar --config-dir=/folder/from/the/previous/step`)
4. Check the color configuration
5. Quit OmegaT
6. Remove the jar from the folder where it was put in step 2
7. Start OmegaT again (the same way as in step 3)

**Expected behavior**
Colors (default or custom) shouldn't change. 

Attached are 6 screenshots, all taken from OmegaT running with a fresh config: 3 with the jar in `plugins` folder, and 3 without the jar.
![withJarColors](https://user-images.githubusercontent.com/6378324/153071193-4622d225-6349-4be1-b76f-cdbcaead8135.png)
![withJarLayouts](https://user-images.githubusercontent.com/6378324/153071199-cc453e13-af24-4984-948a-4a67c7fec74c.png)
![withJarViewMenu](https://user-images.githubusercontent.com/6378324/153071201-8a506924-7da2-4efa-b79c-d5c9fd125c5e.png)
![withoutJarColors](https://user-images.githubusercontent.com/6378324/153071203-3cdcd4fe-40b3-4a08-923e-0ede866e163f.png)
![withoutJarLayouts](https://user-images.githubusercontent.com/6378324/153071205-4a3517bf-c584-4a5b-9a06-019c70e53e31.png)
![withoutJarViewMenu](https://user-images.githubusercontent.com/6378324/153071207-7c2438c4-0ac4-4313-bd10-eb7f80394e44.png)

**System Info**
 - OS: 64-bit GNU/Linux, various DE's, dark GTK theme
 - Java: e.g. Java8, 11, 17, Oracle and OpenJDK
 - OmegaT: v.5.x (released and built from master), all available LAF's

**Comment by kosivantsov** [comment]
Possibly, it's an OmegaT's issue, not the plugin's. I compiled the plugin with nearly the exact copy of OmegaT's `DictionaryGlossaryRenderer.java`, and got the same behaviour.

**Comment by miurahr** [comment]
Could you upload log on console when launching OmegaT? Let's check the order of plugin initializations and whether there are exceptions.

Assumption: 
The renderer plugin might break other plugins initialization.

Because default color themes are implemented as a bundled base plugin, so when plugins initialization process is failed and aborted, a theme would become a OS default,  the behavior would be like as your report.

The base plugins are initialized at last, 
https://github.com/omegat-org/omegat/blob/master/src/org/omegat/filters2/master/PluginUtils.java#L151
It may be skipped when previous part causes unexpected exceptions.

**Comment by miurahr** [comment]
Do you configure `omegat` part of `build.gralde.kts` ? it requires set `className` of your plugin.

**Comment by miurahr** [comment]
The issue, that a default theme is ignored when plugin failed, is fixed in OmegaT nightly.
https://sourceforge.net/p/omegat/bugs/1091/
